on: 
  workflow_dispatch
jobs:
  markdownList:
    name: List open issues labeled "release"
    runs-on: ubuntu-latest
    steps:
      - name: List release issues
        uses: lee-dohm/select-matching-issues@v1
        with:
          format: list
          query: 'label:release is:open'
          token: ${{ github.token }}
