on: 
  workflow_dispatch
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  ListIssues:
    name: List open issues labeled "release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show matching issues
        run: |
          for url in $(gh issue list --label "release" --json number -q '.[] | .number')
          do
            gh issue view --json body,title -q '.title, .body' $url
          done
